# This file is part of Astarte.
#
# Copyright 2024 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "stream-rust-test"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
